version: "2.1"

services:
  app:
    image: irmscher/fspd:v1
    restart: always
    networks:
      - web
      - default
    expose:
      - "9000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:app.docker.localhost"
      - "traefik.basic.port=9000"
      - "traefik.basic.protocol=http"
      - "traefik.admin.frontend.rule=Host:admin-app.docker.localhost"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=9443"
      
networks:
  web:
    external: true
